let array=
[{"id":1,"first_name":"Shalna","email":"screws0@forbes.com","gender":"Female"},
{"id":2,"first_name":"Dita","email":"dnewe1@arizona.edu","gender":"Female"},
{"id":3,"first_name":"Teddi","email":"tbickell2@vkontakte.ru","gender":"Female"},
{"id":4,"first_name":"Vidovic","email":"vleeder3@google.es","gender":"Male"},
{"id":5,"first_name":"Wileen","email":"wcianelli4@ehow.com","gender":"Female"},
{"id":6,"first_name":"Berkeley","email":"bmccrudden5@addthis.com","gender":"Male"},
{"id":7,"first_name":"Hewitt","email":"hfiddian6@intel.com","gender":"Male"},
{"id":8,"first_name":"Alissa","email":"amaasz7@plala.or.jp","gender":"Female"},
{"id":9,"first_name":"Sofia","email":"ssoppeth8@dailymail.co.uk","gender":"Female"},
{"id":10,"first_name":"Elbert","email":"erishworth9@amazonaws.com","gender":"Agender"},
{"id":11,"first_name":"Jacenta","email":"jmarconia@nsw.gov.au","gender":"Female"},
{"id":12,"first_name":"Alecia","email":"anettleb@so-net.ne.jp","gender":"Female"},
{"id":13,"first_name":"Joan","email":"jmeyrickc@guardian.co.uk","gender":"Female"},
{"id":14,"first_name":"Ulrike","email":"uwoltersd@constantcontact.com","gender":"Female"},
{"id":15,"first_name":"Marjory","email":"mwearnee@mediafire.com","gender":"Female"},
{"id":16,"first_name":"Vilma","email":"vantukf@nhs.uk","gender":"Female"},
{"id":17,"first_name":"Sisile","email":"ssineyg@intel.com","gender":"Genderfluid"},
{"id":18,"first_name":"Maible","email":"mhonackerh@ft.com","gender":"Female"},
{"id":19,"first_name":"Franciskus","email":"felphicki@umn.edu","gender":"Male"},
{"id":20,"first_name":"Nicolea","email":"npoizerj@geocities.com","gender":"Female"},
{"id":21,"first_name":"Bette","email":"bfoalek@qq.com","gender":"Female"},
{"id":22,"first_name":"Marthena","email":"mnorcuttl@yahoo.com","gender":"Non-binary"},
{"id":23,"first_name":"Laurianne","email":"lshearmerm@vimeo.com","gender":"Bigender"},
{"id":24,"first_name":"Davie","email":"dbeadelln@e-recht24.de","gender":"Male"},
{"id":25,"first_name":"Edward","email":"eerdelyo@w3.org","gender":"Male"},
{"id":26,"first_name":"Caryl","email":"ceadsp@reddit.com","gender":"Male"},
{"id":27,"first_name":"Ingar","email":"isailorq@netvibes.com","gender":"Male"},
{"id":28,"first_name":"Melisa","email":"mfinchamr@dagondesign.com","gender":"Female"},
{"id":29,"first_name":"Jacquelyn","email":"jsellss@typepad.com","gender":"Female"},
{"id":30,"first_name":"Winna","email":"wbillingtont@tamu.edu","gender":"Female"},
{"id":31,"first_name":"Julio","email":"josbaldstoneu@csmonitor.com","gender":"Male"},
{"id":32,"first_name":"Arnuad","email":"azorerv@rediff.com","gender":"Male"},
{"id":33,"first_name":"Sherwynd","email":"slindnerw@dion.ne.jp","gender":"Male"},
{"id":34,"first_name":"Erie","email":"eesilmonx@symantec.com","gender":"Male"},
{"id":35,"first_name":"Ernst","email":"emurrumy@gnu.org","gender":"Male"},
{"id":36,"first_name":"Wesley","email":"wfealtyz@amazon.com","gender":"Male"},
{"id":37,"first_name":"Nollie","email":"ncaddell10@house.gov","gender":"Male"},
{"id":38,"first_name":"Yehudit","email":"ybollard11@state.gov","gender":"Male"},
{"id":39,"first_name":"Anatol","email":"apretious12@bigcartel.com","gender":"Male"},
{"id":40,"first_name":"Ingrim","email":"ibriton13@meetup.com","gender":"Male"},
{"id":41,"first_name":"Kenyon","email":"kofallowne14@devhub.com","gender":"Genderfluid"},
{"id":42,"first_name":"Nikki","email":"nnormanell15@noaa.gov","gender":"Male"},
{"id":43,"first_name":"Lauritz","email":"lmidgely16@indiegogo.com","gender":"Male"},
{"id":44,"first_name":"Farly","email":"fbelsher17@independent.co.uk","gender":"Male"},
{"id":45,"first_name":"Claire","email":"cmcgookin18@ebay.co.uk","gender":"Male"},
{"id":46,"first_name":"Willem","email":"wgarritley19@github.com","gender":"Male"},
{"id":47,"first_name":"Alexandra","email":"abotting1a@amazon.co.jp","gender":"Female"},
{"id":48,"first_name":"Karylin","email":"keydel1b@disqus.com","gender":"Female"},
{"id":49,"first_name":"Clementina","email":"caggott1c@admin.ch","gender":"Female"},
{"id":50,"first_name":"Valentine","email":"vpetrasek1d@cyberchimps.com","gender":"Male"}
]
function getEmployees()
{
let rows=" "
 for( ARR of array)
    { if(ARR.gender==="Male")
    {
        rows=rows+`<tr><td>${ARR.id}</td>
                        <td>${ARR.first_name}</td>
                        <td>${ARR.email}</td> 
                        <td>${ARR.gender}</td> 
                       </tr>`
    }
    }
document.getElementsByTagName("tbody")[0].innerHTML=rows
}